### ISSUE TITLE
Settings are not stored permanently in the "portable" version.

### ISSUE THREAD

**Issue by BruceBrain** [taskexplorer/TaskExplorer#15]
Hi David,
find your TaskExplorer very helpful and would like to use it more frequently to analyze my PC.

I'm using the Zip Version of the software (v1.2.5) which runs without installation, something I'm prefer.
All settings I'm making to the interface like colums, colors ect. are lost once the program is restarted.
Am I doing something wrong or is there a workaround for this behaviour.
Cheers!
Bruce

**Comment by DavidXanatos** [comment]
mmh... that should actually work, do you mean it looses strings wen moved between PC's or on the same one?

On the same PC it should store a settings file on C:\Users\...\AppData\Local\TaskExplorer
and than it should remember columns etc.

to make it make and use that file in its current directory add an empty TaskExplorer.ini to the folder with TaskExplorer.exe if it finds a file in its own dir it uses it instead of one in the userprofile.

**Comment by DavidXanatos** [comment]
Well its the same binary as the non portable, but i probably should put an empty ini in the zips to triger this behavioure that woulld be indeed better for the users.

glad I could help.

**Comment by Zymlex** [comment]
@DavidXanatos zip file is still missing from the archive, but thanks for this possibility.
